DROP TABLE if EXISTS members CASCADE;
CREATE TABLE members
(
    id                  bigint generated by default as identity,
    login_email         varchar(60) NOT NULL UNIQUE,
    login_password      varchar(60) NOT NULL,
    company_name        varchar(60) NOT NULL,
    role                varchar(30) NOT NULL,
    created_date_time   TIMESTAMP NOT NULL,
    primary key (id)
);

DROP TABLE if EXISTS errors CASCADE;
CREATE TABLE errors
(
    id                  bigint generated by default as identity,
    locale              varchar(2) NOT NULL,
    name                varchar(30) NOT NULL,
    reason              varchar(60) NOT NULL,
    http_status         smallint NOT NULL,
    primary key (id)
);

INSERT INTO errors VALUES (1, 'ko', 'INVALID_INPUT', '유효하지 않은 입력값', 400),
                          (2, 'ko', 'EXIST_MEMBER', '존재하는 이메일', 500);