DROP TABLE if EXISTS members CASCADE;
CREATE TABLE members
(
    id                  BIGINT generated by default as identity,
    login_email         VARCHAR(60) NOT NULL UNIQUE,
    login_password      VARCHAR(60) NOT NULL,
    company_name        VARCHAR(60) NOT NULL,
    role                VARCHAR(30) NOT NULL,
    created_date_time   TIMESTAMP NOT NULL,
    primary key (id)
);

INSERT INTO members VALUES (DEFAULT, 'FBGpx7QTvQ+2vuzMtAvUYT2/UegU7KbhUTlWjnF1xGw=', '$2a$10$o.ELf/cRCuesZ2hWFdAdDOBr0OcZ6oEFD6.JzZyp.JWTM3kDsJYg.', 'tyjf1Z+UA01fHr0ztigw9A==', 'MEMBER', '2024-01-05 13:52:52'),
                          (DEFAULT, 'qdbHE5cw2d2mGv9Zenus4Pv6UM1tW7QsTtyvqDmzKJA=', '$2a$10$u04uFy2x/MiqoJ2OCB/vE.E4AWHYvlKIxMkPGlANZ5g7phvgJ5Ql6', 'tyjf1Z+UA01fHr0ztigw9A==', 'EMAIL_UNAUTHORIZED', '2024-01-04 21:40:11');

DROP TABLE if EXISTS machines CASCADE;
CREATE TABLE machines
(
    id                  BIGINT generated by default as identity,
    machine_name        VARCHAR(20) NOT NULL,
    machine_model       VARCHAR(20),
    date_manufactured   DATE,
    sequence            SMALLINT NOT NULL,
    selected            BOOLEAN DEFAULT FALSE NOT NULL ,
    member_id           BIGINT NOT NULL,
    primary key (id),
    FOREIGN KEY (member_id) REFERENCES members(id)
);

INSERT INTO machines VALUES (DEFAULT, '1호기', 'sss', null, 0, DEFAULT, 1);