DROP TABLE if EXISTS members CASCADE;
CREATE TABLE members
(
    id                  bigint generated by default as identity,
    login_email         varchar(60) NOT NULL UNIQUE,
    login_password      varchar(60) NOT NULL,
    company_name        varchar(60) NOT NULL,
    role                varchar(30) NOT NULL,
    created_date_time   TIMESTAMP NOT NULL,
    primary key (id)
);

INSERT INTO members VALUES (100, 'FBGpx7QTvQ+2vuzMtAvUYT2/UegU7KbhUTlWjnF1xGw=', '$2a$10$o.ELf/cRCuesZ2hWFdAdDOBr0OcZ6oEFD6.JzZyp.JWTM3kDsJYg.', 'tyjf1Z+UA01fHr0ztigw9A==', 'MEMBER', '2024-01-05 13:52:52'),
                          (200, 'qdbHE5cw2d2mGv9Zenus4Pv6UM1tW7QsTtyvqDmzKJA=', '$2a$10$u04uFy2x/MiqoJ2OCB/vE.E4AWHYvlKIxMkPGlANZ5g7phvgJ5Ql6', 'tyjf1Z+UA01fHr0ztigw9A==', 'EMAIL_UNAUTHORIZED', '2024-01-04 21:40:11');
